In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
import urllib.request
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = 'data.csv'
urllib.request.urlretrieve(url, filename)

('data.csv', <http.client.HTTPMessage at 0x17923576370>)

# Question 1
What's the version of NumPy that you installed?

In [4]:
np.__version__

'1.21.5'

In [55]:
df = pd.read_csv('data.csv')

# Question 2
How many records are in the dataset?

In [6]:
df.shape

(11914, 16)

# Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

In [7]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [9]:
df['Make'].value_counts()[0:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Question 4
What's the number of unique Audi car models in the dataset?

In [13]:
df[df['Make']=='Audi']['Model'].nunique()

34

# Question 5
How many columns in the dataset have missing values?

In [14]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

# Question 6
Find the median value of "Engine Cylinders" column in the dataset.
Next, calculate the most frequent value of the same "Engine Cylinders".
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
Now, calculate the median value of "Engine Cylinders" once again.

In [15]:
#Find the median value of "Engine Cylinders" column in the dataset. 
df['Engine Cylinders'].median()

6.0

In [17]:
#calculate the most frequent value of the same "Engine Cylinders". 
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [22]:
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0], inplace=True)

In [24]:
#calculate the median value of "Engine Cylinders" once again.
df['Engine Cylinders'].median()

6.0

# Question 7

In [25]:
#Select all the "Lotus" cars from the dataset.

In [56]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [57]:
df = df[df['Make']=='Lotus']

In [58]:
df = df[["Engine HP", "Engine Cylinders"]]

In [59]:
df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [60]:
df = df.drop_duplicates()

In [108]:
df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [109]:
x = df.to_numpy()

In [110]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [111]:
transpose_x = x.T

In [112]:
transpose_x

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [113]:
xtx = x.dot(transpose_x)

In [114]:
xtx

array([[ 35737.,  41218.,  41029.,  66182.,  75624.,  52188.,  65229.,
         48589.,  45376.],
       [ 41218.,  47540.,  47322.,  76332.,  87224.,  60192.,  75234.,
         56042.,  52336.],
       [ 41029.,  47322.,  47105.,  75982.,  86824.,  59916.,  74889.,
         55785.,  52096.],
       [ 66182.,  76332.,  75982., 122564., 140048.,  96648., 120798.,
         89982.,  84032.],
       [ 75624.,  87224.,  86824., 140048., 160036., 110436., 138036.,
        102824.,  96024.],
       [ 52188.,  60192.,  59916.,  96648., 110436.,  76212.,  95256.,
         70956.,  66264.],
       [ 65229.,  75234.,  74889., 120798., 138036.,  95256., 119061.,
         88689.,  82824.],
       [ 48589.,  56042.,  55785.,  89982., 102824.,  70956.,  88689.,
         66065.,  61696.],
       [ 45376.,  52336.,  52096.,  84032.,  96024.,  66264.,  82824.,
         61696.,  57616.]])

In [115]:
inv = np.linalg.inv(xtx)

In [116]:
transpose_x.shape

(2, 9)

In [117]:
inv.shape

(9, 9)

In [118]:
xtx.shape

(9, 9)

In [119]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [122]:
r = inv.dot(x)

In [126]:
r

array([[ 4.68571870e+17,  8.55350887e+15],
       [-1.42578261e+18, -2.69161725e+16],
       [ 1.07185671e+18,  2.25179981e+16],
       [-8.10647933e+16, -8.44424930e+14],
       [ 4.50560000e+04, -5.12000000e+02],
       [ 2.58781057e+16,  4.71690488e+14],
       [-1.39611588e+17, -1.12589991e+15],
       [ 3.32140473e+16,  5.62949953e+14],
       [-4.16582966e+16, -1.12589991e+15]])